apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: cachingdemo
build:
  artifacts:
  - image: cachingdemo
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
deploy:
  kustomize:
    paths:
    - k8s
