apiVersion: apps/v1
kind: Deployment
metadata:
  name: cachingdemointernal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cachingdemointernal
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cachingdemointernal
      annotations:
        co.elastic.logs/json.keys_under_root: "true"
        co.elastic.logs/json.message_key: "message"
        co.elastic.logs/json.overwrite_keys: "true"
        co.elastic.logs/enabled: "true"
    spec:
      containers:
        - name: cachingdemointernal
          image: cachingdemo
          env:
            - name:  SERVICENAME
              value: cachingdemointernal-service
            - name:  ELASTIC_APM_SERVICE_NAME
              value: cachingdemointernal-service
            - name:  ELASTIC_APM_APPLICATION_PACKAGES
              value: com.hatimonline.*,org.springframework.*
            - name:  ELASTIC_APM_SERVER_URL
              value: http://apmdev-apm-http.devoops.svc.cluster.local:8200
            - name:  ELASTIC_APM_SECRET_TOKEN
              value: "devoops!"
            - name: SPRING_REDIS_HOST
              value: redis-master.default.svc.cluster.local
            - name: SPRING_REDIS_PORT
              value: "6379"
            - name: SPRING_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
          ports:
            - name: http
              containerPort: 8080
            - name: hazelcast
              containerPort: 5701
